image:
  - Visual Studio 2017

platform:
  - x86

environment:
  matrix:
    - nodejs_version: "12"
  GH_TOKEN:
    secure: nHwMgMQEtRz4aOFCd55jOo41s9dXD2S4m9Tf0hohiQFQofo2mJ3KThNyL5HBg/Eb
  ACCESS_TOKEN:
    secure: nHwMgMQEtRz4aOFCd55jOo41s9dXD2S4m9Tf0hohiQFQofo2mJ3KThNyL5HBg/Eb

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@latest
  - npm install -g yarn
  - set PATH=%APPDATA%\npm;%PATH%
  - yarn install

matrix:
  fast_finish: true

skip_tags: true

shallow_clone: true

build_script:
  - npm run build
  - npm run electron:build

artifacts:
  - path: dist_electron\*.exe
    name: bin

cache:
  - node_modules
  - "%LOCALAPPDATA%\\Yarn"
  - '%APPDATA%\npm-cache'
